/////////////////CONSTANTS/////////////////////
const ADD_ENTRY = "ADD_ENTRY";
const EDIT_ENTRY = "EDIT_ENTRY";
const GET_ALL_ENTRIES = "GET_ALL_ENTRIES";
const GET_ALL_WINNING_ENTRIES = "GET_ALL_WINNING_ENTRIES";
const GET_ENTRIES_BY_CATEGORY = "GET_ENTRIES_BY_CATEGORY";
const GET_WINNING_ENTRIES_BY_CATEGORY = "GET_WINNING_ENTRIES_BY_CATEGORY";
const GET_ENTRY = "GET_ENTRY";
const DELETE_ENTRY = "DELETE_ENTRY";
const UPDATE_ENTRY_FIELD = "UPDATE_ENTRY_FIELD";
const SHOW_CONFIRM_DELETE_MODAL = "SHOW_CONFIRM_DELETE_MODAL";
const REPLACE_CURRENT_SELECTED_ENTRY = "REPLACE_CURRENT_SELECTED_ENTRY"

export {
    ADD_ENTRY,
    EDIT_ENTRY,
    GET_ALL_ENTRIES,
    GET_ALL_WINNING_ENTRIES,
    GET_ENTRIES_BY_CATEGORY,
    GET_WINNING_ENTRIES_BY_CATEGORY,
    GET_ENTRY,
    DELETE_ENTRY,
    UPDATE_ENTRY_FIELD,
    SHOW_CONFIRM_DELETE_MODAL,
    REPLACE_CURRENT_SELECTED_ENTRY
}
